SELECT * FROM EMPLOYEES 
WHERE ADDRESS LIKE '%Elgin,IL';

SELECT  * FROM EMPLOYEES
WHERE DEP_ID = 5
AND SALARY BETWEEN 60000 AND 70000;

SELECT  * FROM EMPLOYEES
ORDER BY DEP_ID;

SELECT  * FROM EMPLOYEES
ORDER BY DEP_ID DESC,  L_NAME DESC;

SELECT DEP_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) AS NUM_EMPLOYEES,  AVG(SALARY) AS AVG_SALARY
FROM EMPLOYEES
GROUP BY DEP_ID
HAVING COUNT(*) < 4
ORDER BY AVG_SALARY ;

SELECT  e.*, d.DEP_NAME FROM EMPLOYEES e , DEPARTMENTS d
WHERE e.DEP_ID = d.DEPT_ID_DEP
ORDER BY d.DEP_NAME DESC,  L_NAME DESC;

